<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxFXwac\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxFXwac/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxFXwac.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxFXwac\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxFXwac\App_KernelDevDebugContainer([
    'container.build_hash' => 'UxFXwac',
    'container.build_id' => '9844e5cb',
    'container.build_time' => 1660051071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxFXwac');
