<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAagVQ1N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAagVQ1N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAagVQ1N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAagVQ1N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAagVQ1N\App_KernelDevDebugContainer([
    'container.build_hash' => 'AagVQ1N',
    'container.build_id' => '32ea9869',
    'container.build_time' => 1629828362,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAagVQ1N');
