<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC1USaiC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC1USaiC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC1USaiC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC1USaiC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC1USaiC\App_KernelDevDebugContainer([
    'container.build_hash' => 'C1USaiC',
    'container.build_id' => 'aff72aa2',
    'container.build_time' => 1654947487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC1USaiC');
